# Comprehensive Edge-Case, Sparse Input, and Conflict Profiles for Robustness Testing.
from typing import Any, Dict, List

EDGE_CASE_PROFILES: List[Dict[str, Any]] = [
    # --- ORIGINAL SUITE (EC01 - EC12) ---
    {
        'id': 'EC01',
        'name': 'Strong Science / PCM',
        'subjects': ['Mathematics', 'Physics', 'Chemistry'],
        'skills': ['Logical Thinking', 'Problem Solving', 'Numerical Ability'],
        'interests': ['Technology', 'Engineering', 'Artificial Intelligence & Data'],
        'expected_stream_id': 'S01',
    },
    {
        'id': 'EC02',
        'name': 'Strong Commerce',
        'subjects': ['Accountancy', 'Business Studies', 'Economics', 'Mathematics'],
        'skills': ['Numerical Ability', 'Financial Analysis', 'Time Management'],
        'interests': ['Finance & Accounting', 'Business & Entrepreneurship', 'Economics'],
        'expected_stream_id': 'S04',
    },
    {
        'id': 'EC03',
        'name': 'Strong Humanities',
        'subjects': ['History', 'Political Science', 'English Language & Literature', 'Sociology'],
        'skills': ['Communication', 'Writing', 'Critical Evaluation', 'Active Listening'],
        'interests': ['History & Culture', 'Public Policy & Governance', 'Languages & Literature'],
        'expected_stream_id': 'S06',
    },
    {
        'id': 'EC04',
        'name': 'Science vs Commerce Conflict',
        'subjects': ['Mathematics', 'Physics', 'Economics'],
        'skills': ['Numerical Ability', 'Problem Solving'],
        'interests': ['Engineering', 'Finance & Accounting'],
        'expected_stream_id': 'S01',
    },
    {
        'id': 'EC05',
        'name': 'Science vs Humanities Conflict',
        'subjects': ['Mathematics', 'Physics', 'English Language & Literature'],
        'skills': ['Logical Thinking', 'Communication'],
        'interests': ['Technology', 'Languages & Literature'],
        'expected_stream_id': 'S01',
    },
    {
        'id': 'EC06',
        'name': 'Commerce vs Humanities Conflict',
        'subjects': ['Economics', 'Business Studies', 'English Language & Literature'],
        'skills': ['Financial Analysis', 'Communication'],
        'interests': ['Economics', 'Languages & Literature'],
        'expected_stream_id': 'S05',
    },
    {
        'id': 'EC07',
        'name': 'Minimal Information (1 item each)',
        'subjects': ['Mathematics'],
        'skills': ['Problem Solving'],
        'interests': ['Technology'],
        'expected_stream_id': 'S01',
    },
    {
        'id': 'EC08',
        'name': 'Missing Inputs - Subjects Only',
        'subjects': ['Mathematics', 'Physics', 'Chemistry'],
        'skills': [],
        'interests': [],
        'expected_stream_id': 'S01',
    },
    {
        'id': 'EC09',
        'name': 'Missing Inputs - Skills Only',
        'subjects': [],
        'skills': ['Logical Thinking', 'Problem Solving', 'Numerical Ability'],
        'interests': [],
        'expected_stream_id': 'S01',
    },
    {
        'id': 'EC10',
        'name': 'Missing Inputs - Interests Only',
        'subjects': [],
        'skills': [],
        'interests': ['Technology', 'Engineering', 'Artificial Intelligence & Data'],
        'expected_stream_id': 'S01',
    },
    {
        'id': 'EC11',
        'name': 'Missing Inputs - Subjects + Interests',
        'subjects': ['Mathematics', 'Physics', 'Chemistry'],
        'skills': [],
        'interests': ['Technology', 'Engineering'],
        'expected_stream_id': 'S01',
    },
    {
        'id': 'EC12',
        'name': 'Missing Inputs - Subjects + Skills',
        'subjects': ['Mathematics', 'Physics', 'Chemistry'],
        'skills': ['Logical Thinking', 'Problem Solving'],
        'interests': [],
        'expected_stream_id': 'S01',
    },

    # --- TASK 3 SPARSE & INCOMPLETE SUITE (EC13 - EC22) ---
    {
        'id': 'EC13',
        'name': 'Sparse Input - Skills Only',
        'subjects': [],
        'skills': ['Numerical Ability', 'Financial Analysis'],
        'interests': [],
        'expected_stream_id': 'S04',
    },
    {
        'id': 'EC14',
        'name': 'Sparse Input - Interests Only',
        'subjects': [],
        'skills': [],
        'interests': ['Finance & Accounting', 'Investments & Banking'],
        'expected_stream_id': 'S04',
    },
    {
        'id': 'EC15',
        'name': 'Sparse Input - Skills + Interests',
        'subjects': [],
        'skills': ['Communication', 'Writing'],
        'interests': ['History & Culture', 'Languages & Literature'],
        'expected_stream_id': 'S06',
    },
    {
        'id': 'EC16',
        'name': 'Sparse Input - Only 1 Subject',
        'subjects': ['Biology'],
        'skills': [],
        'interests': [],
        'expected_stream_id': 'S02',
    },
    {
        'id': 'EC17',
        'name': 'Sparse Input - Only 1 Skill',
        'subjects': [],
        'skills': ['Creativity'],
        'interests': [],
        'expected_stream_id': 'S07',
    },
    {
        'id': 'EC18',
        'name': 'Sparse Input - Only 1 Interest',
        'subjects': [],
        'skills': [],
        'interests': ['Journalism & Mass Media'],
        'expected_stream_id': 'S12',
    },
    {
        'id': 'EC19',
        'name': 'Empty Profile',
        'subjects': [],
        'skills': [],
        'interests': [],
        'expected_stream_id': 'S01', # Default fallback candidate
    },

    # --- TASK 4 DOMAIN CONFLICT SUITE (EC20 - EC24) ---
    {
        'id': 'EC20',
        'name': 'Technology + Finance Conflict',
        'subjects': ['Mathematics', 'Computer Science', 'Accountancy'],
        'skills': ['Programming', 'Financial Analysis'],
        'interests': ['Artificial Intelligence & Data', 'Investments & Banking'],
        'expected_stream_id': 'S01',
    },
    {
        'id': 'EC21',
        'name': 'Engineering + Business Conflict',
        'subjects': ['Physics', 'Business Studies'],
        'skills': ['Troubleshooting & Debugging', 'Entrepreneurial Thinking'],
        'interests': ['Robotics & Automation', 'Business & Entrepreneurship'],
        'expected_stream_id': 'S01',
    },
    {
        'id': 'EC22',
        'name': 'Mathematics + Biology (PCM vs PCB) Conflict',
        'subjects': ['Mathematics', 'Biology', 'Physics', 'Chemistry'],
        'skills': ['Logical Thinking', 'Diagnostic Acumen'],
        'interests': ['Technology', 'Medicine & Healthcare'],
        'expected_stream_id': 'S03', # Interdisciplinary PCMB
    },

    # --- TASK 9 UNKNOWN / INVALID INPUT SUITE (EC23 - EC25) ---
    {
        'id': 'EC23',
        'name': 'Invalid / Unknown Skill Names',
        'subjects': ['Mathematics', 'Physics'],
        'skills': ['Superpower Mastery', 'Quantum Teleportation'],
        'interests': ['Technology'],
        'expected_stream_id': 'S01',
    },
    {
        'id': 'EC24',
        'name': 'Invalid / Unknown Interest Names',
        'subjects': ['Accountancy', 'Economics'],
        'skills': ['Financial Analysis'],
        'interests': ['Time Travel Operations', 'Alien Communication'],
        'expected_stream_id': 'S04',
    },
    {
        'id': 'EC25',
        'name': 'Invalid / Unknown Subjects',
        'subjects': ['Alchemy 101', 'Astrology Studies'],
        'skills': ['Communication'],
        'interests': ['History & Culture'],
        'expected_stream_id': 'S06',
    },
]
